SET IDENTITY_INSERT [dbo].[CarType] ON
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (1, N'Hatchback')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (2, N'Sedan')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (3, N'Coupe')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (4, N'SUV')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (5, N'Convertible')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (6, N'Crossover')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (7, N'Pickup')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (8, N'Minivan')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (9, N'Sports car')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (10, N'Van')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (11, N'Roadster')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (12, N'Compact')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (13, N'Supercar')
INSERT INTO [dbo].[CarType] ([Id], [Name]) VALUES (14, N'Muscle car')
SET IDENTITY_INSERT [dbo].[CarType] OFF
