//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carstore.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarstoreDBEntities : DbContext
    {
        public CarstoreDBEntities()
            : base("name=CarstoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarMark> CarMark { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<CarPhoto> CarPhoto { get; set; }
        public virtual DbSet<CarProposition> CarProposition { get; set; }
        public virtual DbSet<CarType> CarType { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<DetailProposition> DetailProposition { get; set; }
        public virtual DbSet<DetailType> DetailType { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
